grafana_version: "12.0.0" # Latest to present day
grafana_admin_user: admin
grafana_admin_password: admin
grafana_port: 3000
grafana_datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://localhost:9090
    is_default: true