- name: Installing required packages
  apt:
    name: 
      - apt-transport-https
      - software-properties-common
      - wget
    state: present
  when: ansible_facts['os_family'] == "Debian"
    
- name: Adding Grafana GPG key
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Adding Grafana repository
  apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Installing Grafana
  apt:
    name: grafana
    state: present
    update_cache: yes
  when: ansible_distribution == "Ubuntu" and ansible_distribution_version is version('18.04', '>=')
  notify: Restart grafana

- name: Creating Grafana datasource configuration directory
  file:
    path: /etc/grafana/provisioning/datasources
    state: directory
    mode: '0755'

- name: Ensure Grafana is started and enabled
  systemd:
    name: grafana-server
    state: started
    enabled: yes