prometheus_version: 3.3.1 # Latest to this day
prometheus_web_listen_address: "0.0.0.0:9090"
prometheus_storage_retention: "2d"

prometheus_scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['10.0.1.4:9100', '10.0.1.5:9100']