- name: Configuration of Near-RT RIC
  hosts: ric_node
  become: yes
  tasks:
    - name: Installing Docker (without recommended packages)
      apt:
        name:
          - docker.io
          - docker-compose
        state: present
        install_recommends: no
      tags: [docker, install]
    
    - name: Ensure Docker is enabled and started
      systemd:
        name: docker.service
        enabled: yes
        state: started
      tags: [docker, systemd]
    
    - name: Configuring Docker logging limits
      copy:
        dest: /etc/docker/daemon.json
        content: |
          {
            "log-driver": "json-file",
            "log-opts": {
              "max-size": "10m",
              "max-file": "3"
            }
          }
        mode: '0644'  
      notify: Restart Docker
      tags: [docker, logging]
    
    - name: Creating directory for Docker tuning
      file:
        path: /etc/systemd/system/docker.service.d
        state: directory
        mode: '0755'  
      tags: [docker, systemd]
    
    - name: Limit Docker resources
      copy:
        dest: /etc/systemd/system/docker.service.d/memory-limits.conf
        content: |
          [Service]
          ExecStart=
          ExecStart=/usr/bin/dockerd --default-shm-size=64M
        mode: '0644' 
      notify: Restart Docker
      tags: [docker, limits]
    
    - name: Clone Near-RT RIC repository
      git:
        repo: https://github.com/wineslab/colosseum-near-rt-ric
        dest: /opt/colosseum-near-rt-ric
        version: ns-o-ran
        force: yes
      tags: [ric, clone]
    
    - name: Check if docker-compose.yaml exists
      stat:
        path: /opt/colosseum-near-rt-ric/setup-scripts/docker-compose.yaml
      register: compose_file
      tags: [ric, docker]
    
    - name: Find docker-compose.yaml location if not in expected path
      find:
        paths: /opt/colosseum-near-rt-ric
        patterns: "docker-compose*.y*ml"
        recurse: yes
      register: compose_file_search
      when: not compose_file.stat.exists
      tags: [ric, docker]
    
    - name: Display found docker-compose file
      debug:
        msg: "Found docker-compose files: {{ compose_file_search.files | map(attribute='path') | list }}"
      when: not compose_file.stat.exists and compose_file_search.matched > 0
      tags: [ric, docker]
    
    - name: Create directory for script logs
      file:
        path: /var/log/ric-setup
        state: directory
        mode: '0755'
      tags: [ric, deploy]

    - name: Import and tag Docker images
      shell:
        cmd: ./import-wines-images.sh
        chdir: /opt/colosseum-near-rt-ric/setup-scripts
      args:
        creates: /tmp/ric_images_imported_flag
      register: import_result
      environment:
        DOCKER_OPTS: "--config /etc/docker" 
      tags: [ric, deploy]
    
    - name: Create import flag file
      file:
        path: /tmp/ric_images_imported_flag
        state: touch
        mode: '0644'
      when: import_result.changed
      tags: [ric, deploy]
    
    - name: Setup and launch RIC
      shell:
        cmd: ./setup-ric-bronze.sh
        chdir: /opt/colosseum-near-rt-ric/setup-scripts
      args:
        creates: /tmp/ric_setup_completed_flag
      register: setup_result
      environment:
        DOCKER_OPTS: "--config /etc/docker"
      tags: [ric, deploy]
    
    - name: Create setup flag file
      file:
        path: /tmp/ric_setup_completed_flag
        state: touch
        mode: '0644'
      when: setup_result.changed
      tags: [ric, deploy]
  
  handlers:
    - name: Restart Docker
      systemd:
        name: docker
        state: restarted
        daemon_reload: yes
      tags: [docker]