name: Infrastructure CI/CD

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0

      - name: Terraform Format Checking
        run: terraform fmt -check
        working-directory: terraform

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: terraform
  
  ansible:
    runs-on: ubuntu-latest
    needs: terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      # Verificar la sintaxis de cada playbook individualmente
      - name: Verify Ansible syntax - Base Configuration
        run: ansible-playbook --syntax-check azure-01-base-configuration.yml

      - name: Verify Ansible syntax - RIC Installation
        run: ansible-playbook --syntax-check azure-02-ric-installation.yml

      - name: Verify Ansible syntax - RIC Deployment
        run: ansible-playbook --syntax-check azure-03-ric-deployment.yml

      - name: Verify Ansible syntax - RAN Configuration
        run: ansible-playbook --syntax-check azure-04-ran-configuration.yml

      - name: Verify Ansible syntax - Monitoring
        run: ansible-playbook --syntax-check azure-05-monitoring.yml