name: Infrastructure CI/CD

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0

      - name: Terraform Format Checking
        run: terraform fmt -check
        working-directory: terraform

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: terraform
  
  ansible:
    runs-on: ubuntu-latest
    needs: terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List directory contents (debug)
        run: |
          echo "=== Root directory ==="
          ls -la
          echo "=== All YAML files recursively ==="
          find . -name "*.yml" | sort

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible
      
      # Intenta con rutas absolutas
      - name: Verify Ansible syntax with absolute paths
        run: |
          REPO_ROOT="$(pwd)"
          echo "Repository root: $REPO_ROOT"
          
          if [ -f "$REPO_ROOT/azure-01-base-configuration.yml" ]; then
            echo "Playbook encontrado en la raíz"
            ansible-playbook --syntax-check "$REPO_ROOT/azure-01-base-configuration.yml"
          elif [ -f "$REPO_ROOT/ansible/azure-01-base-configuration.yml" ]; then
            echo "Playbook encontrado en /ansible"
            ansible-playbook --syntax-check "$REPO_ROOT/ansible/azure-01-base-configuration.yml"
          else
            echo "Buscando playbook recursivamente..."
            PLAYBOOK_PATH=$(find "$REPO_ROOT" -name "azure-01-base-configuration.yml" | head -n 1)
            
            if [ -n "$PLAYBOOK_PATH" ]; then
              echo "Playbook encontrado en: $PLAYBOOK_PATH"
              ansible-playbook --syntax-check "$PLAYBOOK_PATH"
            else
              echo "ERROR: No se pudo encontrar el playbook azure-01-base-configuration.yml"
              exit 1
            fi
          fi