name: Infrastructure CI/CD

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0

      - name: Terraform Format Checking
        run: terraform fmt -check
        working-directory: terraform

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: terraform
  
  ansible:
    runs-on: ubuntu-latest
    needs: terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      # Syntax verification for all of the playbooks in our ansible directory
      - name: Verify Ansible syntax for all playbooks
        run: |
          echo "Verifying all of the playbooks in the ansible directory/"
          for playbook in ansible/azure-*.yml; do
            echo "Checking syntax for $playbook..."
            ansible-playbook --syntax-check "$playbook"
          done